version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5.5
    working_directory: ~/repo
    steps:
      - checkout
      - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - run: sudo python get-pip.py
      - run: pip install --upgrade --user awscli
      - run: pip install --upgrade --user awsebcli
      - run: export PATH=~/.local/bin:$PATH
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run: sudo php composer-setup.php --quiet --filename composer
      #- run: sudo apt-get install php-sqlite3
        # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: php composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      #run tests
      - run: ./vendor/bin/phpunit
      - run: ~/.local/bin/eb deploy
