version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run: sudo php composer-setup.php --quiet --filename composer
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: php composer install
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

  deploy:
    docker:
      - image: circleci/php:5.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: "sudo apt-get update && sudo apt-get upgrade"
      - run:
          name: install python
          command: |
            sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
            curl -O https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tar.xz
            tar -xf Python-3.8.0.tar.xz
            cd Python-3.8.0
            ./configure --enable-optimizations
            make
            sudo make altinstall
            cd ..
      # - run: "sudo apt-get install python3.7 -y"
      - run: "curl https://bootstrap.pypa.io/get-pip.py"
      - run: "sudo apt-get install python3-pip"
      - run: "pip3 install --upgrade --user awscli"
      - run: "pip3 install --upgrade --user awsebcli"
      - run: export PATH=~/.local/bin:$PATH
      - run: echo "REVISION=$CIRCLE_SHA1" > rev.txt
      - run:
          name: deploy
          command: |
            LABEL_NAME=polr-$CIRCLE_BRANCH-$(date '+%Y%m%d_%H%M%S')
            git archive --format=zip HEAD > polr.zip
            zip -ru polr.zip rev.txt
            ~/.local/bin/eb deploy --staged --label=$LABEL_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - development
                - master
          requires:
            - build
