name: Deploy
on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Generate deployment package
        run: zip deploy.zip -r * .[^.]* -x "vendor/*"

      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Use current time
        run: echo "::set-env name=TIME::${{ steps.current-time.outputs.time }}"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Shortener
          environment_name: short-dev
          version_label: ${{ env.TIME }}-short-dev
          region: us-east-1
          deployment_package: deploy.zip
